TMA 5.01 Fixes
intel/perfmon pull request #244
Opened 2024-11-14 20:36 UTC by calebbiggers

- Fixes brief descriptions ending in periods
- Fixes missing thresholds
- Fixes incorrect visibility for GRR file

2024-11-14 20:43 UTC, captain5050 approved these changes

2024-11-15 04:32 UTC, edwarddavidbaker approved these changes

2024-11-15 04:55 UTC, edwarddavidbaker requested changes
Two metric thresholds on SKX and CLX look strange. Highlighted via `create_perf_json.py` failures. I assume it should be `tma_code_stlb_hit > 5` but defer to Caleb regarding `& p`.

```json
    {
        "BriefDescription": "This metric roughly estimates the fraction of cycles where the (first level) ITLB was missed by instructions fetches, that later on hit in second-level TLB (STLB)",
        "MetricExpr": "max( 0 , tma_itlb_misses - tma_code_stlb_miss )",
        "MetricGroup": "FetchLat;MemoryTLB;TopdownL4;tma_L4_group;tma_itlb_misses_group",
        "MetricName": "tma_code_stlb_hit",
        "ScaleUnit": "100%",
        "MetricThreshold": "> 5 & p"
    },
    {
        "BriefDescription": "This metric estimates the fraction of cycles where the Second-level TLB (STLB) was missed by instruction fetches, performing a hardware page walk",
        "MetricExpr": "ITLB_MISSES.WALK_ACTIVE / tma_info_thread_clks",
        "MetricGroup": "FetchLat;MemoryTLB;TopdownL4;tma_L4_group;tma_itlb_misses_group",
        "MetricName": "tma_code_stlb_miss",
        "ScaleUnit": "100%",
        "MetricThreshold": "> 5 & p"
    },
```

2024-11-15 14:37 UTC, 1perrytaylor commented
> Two metric thresholds on SKX and CLX look strange. Highlighted via `create_perf_json.py` failures. I assume it should be `tma_code_stlb_hit > 5` but defer to Caleb regarding `& p`.
> 
> ```json
>     {
>         "BriefDescription": "This metric roughly estimates the fraction of cycles where the (first level) ITLB was missed by instructions fetches, that later on hit in second-level TLB (STLB)",
>         "MetricExpr": "max( 0 , tma_itlb_misses - tma_code_stlb_miss )",
>         "MetricGroup": "FetchLat;MemoryTLB;TopdownL4;tma_L4_group;tma_itlb_misses_group",
>         "MetricName": "tma_code_stlb_hit",
>         "ScaleUnit": "100%",
>         "MetricThreshold": "> 5 & p"
>     },
>     {
>         "BriefDescription": "This metric estimates the fraction of cycles where the Second-level TLB (STLB) was missed by instruction fetches, performing a hardware page walk",
>         "MetricExpr": "ITLB_MISSES.WALK_ACTIVE / tma_info_thread_clks",
>         "MetricGroup": "FetchLat;MemoryTLB;TopdownL4;tma_L4_group;tma_itlb_misses_group",
>         "MetricName": "tma_code_stlb_miss",
>         "ScaleUnit": "100%",
>         "MetricThreshold": "> 5 & p"
>     },
> ```

Thanks Ed. We are working on an update.

2024-11-18 19:22 UTC, 1perrytaylor approved these changes

2024-11-18 20:01 UTC, edwarddavidbaker approved these changes

2024-11-18 20:02 UTC, merged