Spelling fixes
intel/perfmon pull request #44
Opened 2023-01-22 11:57 UTC by diederikdehaas

Fix various spelling errors as reported by Debian's lintian tool.

Condtional -> Conditional
Interal -> Internal
adderted -> asserted
cummulative -> cumulative
casued -> caused
exlusive -> exclusive
occurance -> occurrence
occured -> occurred
occurences -> occurrences
onthe -> on the
preceeding -> preceding
reponses -> responses
satisifed -> satisfied
successfuly -> successfully
transfered -> transferred
transfering -> transferring

Link: https://lore.kernel.org/lkml/20230121184648.38487-1-didi.debian@cknow.org/
Signed-off-by: Diederik de Haas <didi.debian@cknow.org>

2023-01-23 16:08 UTC, edwarddavidbaker requested changes
@diederikdehaas Thank you for creating the pull request. I'll also add the spelling checks to our release tooling. Event list files are generated from an Intel database. The overall flow is roughly the following.
```
Intel database -> Intel repo -> This repo
```

* Broadwell and Cascade Lake platforms need to be generated from the database.
* TMA files also need to be updated internally and then synced to this repo.
* JKT, KNL, KNM, SLM, and WSM-EP-DP can be updated here. I'll merge your suggestions into our internal repo as well.

2023-01-23 16:08 UTC, edwarddavidbaker commented on KNL/events/KnightsLanding_core.json
> +      "BriefDescription": "Counts the number of core cycles the fetch stalls because of an icache miss. This is a cumulative count of core cycles the fetch stalled for all icache misses. ",
Looks good to me. Please increase the version in the header at the top of this file.

2023-01-23 16:08 UTC, edwarddavidbaker commented on KNL/events/KnightsLanding_matrix.json
> +      "DESCRIPTION": "accounts for responses from snoop request hit with data forwarded from its Near-other tile L2 in E/F/M state"
Looks good to me. Please increase the version in the header at the top of this file.

2023-01-23 16:08 UTC, edwarddavidbaker commented on KNL/events/KnightsLanding_uncore.json
> +      "BriefDescription": "Counts the number of entries successfully inserted into the TOR that match  qualifications specified by the subevent -IRQ",
Looks good to me. Please increase the version in the header at the top of this file.

2023-01-23 16:08 UTC, edwarddavidbaker commented on KNM/events/KnightsLanding_core.json
> +      "BriefDescription": "Counts the number of core cycles the fetch stalls because of an icache miss. This is a cumulative count of core cycles the fetch stalled for all icache misses. ",
Looks good to me. Please increase the version in the header at the top of this file.

2023-01-23 16:08 UTC, edwarddavidbaker commented on KNM/events/KnightsLanding_matrix.json
> +      "DESCRIPTION": "accounts for responses from snoop request hit with data forwarded from its Near-other tile L2 in E/F/M state"
Looks good to me. Please increase the version in the header at the top of this file.

2023-01-23 16:08 UTC, edwarddavidbaker commented on KNM/events/KnightsLanding_uncore.json
> +      "BriefDescription": "Counts the number of entries successfully inserted into the TOR that match  qualifications specified by the subevent -IRQ",
Looks good to me. Please increase the version in the header at the top of this file.

2023-01-23 16:08 UTC, edwarddavidbaker commented on SLM/events/Silvermont_core.json
> +      "PublicDescription": "The BACLEARS event counts the number of times the front end is resteered, mainly when the Branch Prediction Unit cannot provide a correct prediction and this is corrected
Looks good to me. Please increase the version in the header at the top of this file.

2023-01-23 16:08 UTC, edwarddavidbaker commented on WSM-EP-DP/events/WestmereEP-DP_core.json
> +      "BriefDescription": "DTLB misses caused by low part of address",
Looks good to me. Please increase the version in the header at the top of this file.

2023-01-23 20:04 UTC, kshiprab commented
Intel folks should be responsible for updating Version and DatePublished in headers when merging the pull request since we are the data owners of event files.

2023-01-23 20:31 UTC, diederikdehaas commented
IOW: The changes that I'm requested to make is this?
> Should I remove the file(s) maintained internally and those that are actively released from the DB from this PR?

2023-01-23 20:43 UTC, diederikdehaas commented
I just pushed the requested changes (assuming my last message was correct).

No longer fixed in this PR:
```
occurance -> occurrence
occured -> occurred
onthe -> on the
satisifed -> satisfied
```

2023-01-23 20:47 UTC, diederikdehaas commented on Atom_TMA.csv
> +Info.Inst_Mix,IpBranch,,,,INST_RETIRED.ANY / BR_INST_RETIRED.ALL_BRANCHES,INST_RETIRED.ANY / BR_INST_RETIRED.ALL_BRANCHES,,,Instructions per Branch (lower number means higher occurrence rate), ,
Both the TMA files have been removed from this PR as well as the files related to Broadwell and Cascade Lake.
I guess I need to resolve all conversations, but all the others will be without a comment like this.

2023-01-23 20:51 UTC, diederikdehaas commented on JKT/events/Jaketown_uncore.json
> +      "PublicDescription": "Counts the number of entries successfully inserted into the TOR that match  qualifications specified by the subevent.  There are a number of subevent 'filters' but only a
As @kshiprab has an intel.com email address on their GH profile, I assumed that they spoke on behalf of this repo maintainers [here](https://github.com/intel/perfmon/pull/44#issuecomment-1400906404), so I did not increase the version in the header. I'll leave that up to you.

2023-01-23 20:55 UTC, diederikdehaas commented
I resolved all the conversations, but it still lists *Changes requested*. I don't know if and if so what else I need to do.
If it's something I need to do, please point out what and where.

2023-01-24 15:45 UTC, edwarddavidbaker commented
Thanks for updating the PR @diederikdehaas and for trimming the changes to JKT, KNL, KNM, and WSM-EP-DP. I'll take a look today.

Do you think you could grant me access to your branch? I'd like to add a few more spelling fixes and also bump versions/dates in the header field. Otherwise I can submit a follow-up PR with the remaining updates.

As an example JKT has additional spelling fixes scheduled.
```
perfmon/JKT/events$ git checkout diederik-fork/spelling-fixes
perfmon/JKT/events$ spellcheck-helper.sh | grep == | cut -d':' -f3 | sort | uniq -c | sort -n
      1  Accumultes ==> Accumulates
      1  conjuection ==> conjunction
      1  credts ==> credits
      1  erros ==> errors
      1  happenning ==> happening
      2  MULsand ==> muls and
      2  inavailability ==> unavailability
      2  noncachaeble ==> non-cacheable, uncacheable, noncacheable
      2  oustandings ==> outstandings, outstanding
      3  acquried ==> acquired
      3  threshholding ==> thresholding
      9  cachable ==> cacheable
     11  Sequenser ==> Sequencer
     13  trasmitted ==> transmitted
```

2023-01-25 21:36 UTC, edwarddavidbaker commented
Thanks for granting access @diederikdehaas . I'll try to work on the remaining spelling issues for these platforms.

2023-01-27 15:36 UTC, edwarddavidbaker commented
Sorry about the delays, I added a few more commits to your branch. The branch was rebased due to changes in `mapfile.csv`. Running a few final checks and will then merge.

2023-01-27 16:03 UTC, edwarddavidbaker approved these changes
LGTM.

2023-01-27 16:03 UTC, merged

2023-05-07 20:57 UTC, diederikdehaas commented
Just looked at the latest merge for 6.4-rc1 and what I do I see? ``occurance`` :-/

2023-05-08 04:12 UTC, edwarddavidbaker commented
Thanks for checking @diederikdehaas. I currently see instances of `occurance` in TMA related metric files in this repository. We will include them in our spelling checks.

```
$ grep -rn occurance
E-core_TMA_Metrics.csv:64:Info.Inst_Mix,IpBranch,,,,INST_RETIRED.ANY / BR_INST_RETIRED.ALL_BRANCHES,,,Instructions per Branch (lower number means higher occurance rate), ,
E-core_TMA_Metrics.csv:65:Info.Inst_Mix,IpCall,,,,INST_RETIRED.ANY / BR_INST_RETIRED.CALL,,,Instruction per (near) call (lower number means higher occurance rate), ,
Atom_TMA.csv:50:Info.Inst_Mix,IpBranch,,,,INST_RETIRED.ANY / BR_INST_RETIRED.ALL_BRANCHES,INST_RETIRED.ANY / BR_INST_RETIRED.ALL_BRANCHES,,,Instructions per Branch (lower number means higher occurance rate), ,
Atom_TMA.csv:51:Info.Inst_Mix,IpCall,,,,INST_RETIRED.ANY / BR_INST_RETIRED.CALL,INST_RETIRED.ANY / BR_INST_RETIRED.CALL,,,Instruction per (near) call (lower number means higher occurance rate), ,
```

2023-05-08 09:37 UTC, diederikdehaas commented
Ideally you'd link to ``scripts/spelling.txt`` in Linus' ``master`` branch, but copying from there would also work.